import { Agent, AgentName, AgentStatus } from './types';

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'planning',
    name: AgentName.PLANNING,
    description: "Gathers user preferences and designs a tailored wedding workflow.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Finalize Guest List", "Choose Wedding Theme", "Set a Date"],
  },
  {
    id: 'vendor',
    name: AgentName.VENDOR,
    description: "Automates vendor discovery, communication, booking, and follow-ups.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Find Photographers", "Request Catering Quotes", "Book a Florist"],
  },
  {
    id: 'checklist',
    name: AgentName.CHECKLIST,
    description: "Tracks milestones, sends reminders, and manages dynamic task lists.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Add 'Send Invitations' Task", "Mark 'Venue Booked' as Done"],
  },
  {
    id: 'budget',
    name: AgentName.BUDGET,
    description: "Monitors expenses, provides financial insights, and sends budget alerts.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Log a New Expense", "Review Spending by Category"],
  },
  {
    id: 'guest',
    name: AgentName.GUEST,
    description: "Handles RSVPs, guest communication, seating arrangements, and dietary needs.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Send RSVP Reminders", "Update Seating Chart"],
  },
  {
    id: 'notification',
    name: AgentName.NOTIFICATION,
    description: "Sends timely alerts and updates to all stakeholders.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Send Update to Couple", "Alert Planner of Overdue Task"],
  },
  {
    id: 'social',
    name: AgentName.SOCIAL,
    description: "Crafts and publishes wedding announcements and updates across social media platforms.",
    status: AgentStatus.IDLE,
    log: [],
    sampleTasks: ["Draft '1 Month To Go!' Post", "Schedule Rehearsal Dinner Post"],
  }
];

export const SIMULATION_SCRIPT: { agent: AgentName; message: string; delay: number; status?: AgentStatus; targetStatus?: AgentStatus }[] = [
    { agent: AgentName.PLANNING, message: "Initializing... Gathering user preferences.", delay: 1000, status: AgentStatus.WORKING },
    { agent: AgentName.PLANNING, message: "Preferences received: Theme 'Classic Elegance', 150 guests, Budget $30,000.", delay: 2000, status: AgentStatus.COMPLETED },
    { agent: AgentName.CHECKLIST, message: "Creating personalized wedding checklist.", delay: 500, status: AgentStatus.WORKING },
    { agent: AgentName.BUDGET, message: "Setting up budget tracker based on $30,000 limit.", delay: 500, status: AgentStatus.WORKING },
    { agent: AgentName.CHECKLIST, message: "Checklist created. First milestone: 'Book Venue'.", delay: 1500, status: AgentStatus.COMPLETED },
    { agent: AgentName.BUDGET, message: "Budget allocated across categories.", delay: 1500, status: AgentStatus.COMPLETED },
    { agent: AgentName.VENDOR, message: "Searching for venues matching 'Classic Elegance' theme for 150 guests.", delay: 1000, status: AgentStatus.WORKING },
    { agent: AgentName.NOTIFICATION, message: "Alert sent: Welcome to your AI Wedding Plan!", delay: 500, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.VENDOR, message: "Found 5 potential venues. Analyzing contracts...", delay: 2500 },
    { agent: AgentName.VENDOR, message: "Venue option 'The Skyline Loft' matches all criteria.", delay: 1500 },
    { agent: AgentName.BUDGET, message: "Analyzing 'The Skyline Loft' quote against budget.", delay: 500, status: AgentStatus.WORKING },
    { agent: AgentName.BUDGET, message: "Quote is within venue budget. Recommendation: Proceed.", delay: 2000, status: AgentStatus.COMPLETED },
    { agent: AgentName.VENDOR, message: "Recommendation sent to user for 'The Skyline Loft'.", delay: 1000, status: AgentStatus.COMPLETED },
    { agent: AgentName.GUEST, message: "Preparing guest list import and RSVP system.", delay: 1000, status: AgentStatus.WORKING },
    { agent: AgentName.CHECKLIST, message: "Milestone updated: 'Venue' pending user approval.", delay: 500, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.GUEST, message: "RSVP portal is now live.", delay: 2000, status: AgentStatus.COMPLETED },
    { agent: AgentName.SOCIAL, message: "Drafting 'Save the Date' announcement with RSVP link.", delay: 1500, status: AgentStatus.WORKING },
    { agent: AgentName.SOCIAL, message: "Publishing to Facebook...", delay: 1000 },
    { agent: AgentName.SOCIAL, message: "Publishing to Instagram...", delay: 1000 },
    { agent: AgentName.SOCIAL, message: "Updating wedding website...", delay: 1000 },
    { agent: AgentName.SOCIAL, message: "Announcements are live across all platforms!", delay: 500, status: AgentStatus.COMPLETED, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.NOTIFICATION, message: "FYI: 'Save the Date' has been published on social media.", delay: 500, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.VENDOR, message: "User approved 'The Skyline Loft'. Initiating booking process.", delay: 3000, status: AgentStatus.WORKING },
    { agent: AgentName.BUDGET, message: "Expense logged: Venue deposit - $5,000.", delay: 500, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.CHECKLIST, message: "Milestone completed: 'Book Venue' ✅", delay: 500, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.VENDOR, message: "Venue booked! Now searching for caterers...", delay: 2000, status: AgentStatus.WORKING },
    { agent: AgentName.GUEST, message: "RSVP received: John & Jane Smith - Attending.", delay: 4000, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.BUDGET, message: "Catering quote received from 'Gourmet Delights' - $12,000.", delay: 5000, status: AgentStatus.WORKING },
    { agent: AgentName.BUDGET, message: "ALERT: Catering quote is 20% over budget!", delay: 1000, status: AgentStatus.ALERT },
    { agent: AgentName.NOTIFICATION, message: "Budget Alert sent: Catering quote exceeds allocation by 20%.", delay: 500, status: AgentStatus.WORKING, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.VENDOR, message: "Negotiating with 'Gourmet Delights' based on budget alert.", delay: 1000, status: AgentStatus.WORKING },
    { agent: AgentName.VENDOR, message: "New quote received. Price reduced by 15%. Within acceptable range.", delay: 3000, status: AgentStatus.COMPLETED, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.BUDGET, message: "Budget status is now green.", delay: 500, status: AgentStatus.COMPLETED, targetStatus: AgentStatus.IDLE },
    { agent: AgentName.PLANNING, message: "All major milestones on track. Project status: Green.", delay: 2000, status: AgentStatus.IDLE }
];